package com.telrob.common.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class AppDevice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.project_id
	 * @mbg.generated
	 */
	private Integer projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.product_id
	 * @mbg.generated
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.device_secret
	 * @mbg.generated
	 */
	private String deviceSecret;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.mac
	 * @mbg.generated
	 */
	private String mac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.state
	 * @mbg.generated
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.modify_time
	 * @mbg.generated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.c_time
	 * @mbg.generated
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date cTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_device.topic
	 * @mbg.generated
	 */
	private String topic;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.id
	 * @return  the value of app_device.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.id
	 * @param id  the value for app_device.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.user_id
	 * @return  the value of app_device.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.user_id
	 * @param userId  the value for app_device.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.project_id
	 * @return  the value of app_device.project_id
	 * @mbg.generated
	 */
	public Integer getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.project_id
	 * @param projectId  the value for app_device.project_id
	 * @mbg.generated
	 */
	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.product_id
	 * @return  the value of app_device.product_id
	 * @mbg.generated
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.product_id
	 * @param productId  the value for app_device.product_id
	 * @mbg.generated
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.device_secret
	 * @return  the value of app_device.device_secret
	 * @mbg.generated
	 */
	public String getDeviceSecret() {
		return deviceSecret;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.device_secret
	 * @param deviceSecret  the value for app_device.device_secret
	 * @mbg.generated
	 */
	public void setDeviceSecret(String deviceSecret) {
		this.deviceSecret = deviceSecret == null ? null : deviceSecret.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.name
	 * @return  the value of app_device.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.name
	 * @param name  the value for app_device.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.mac
	 * @return  the value of app_device.mac
	 * @mbg.generated
	 */
	public String getMac() {
		return mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.mac
	 * @param mac  the value for app_device.mac
	 * @mbg.generated
	 */
	public void setMac(String mac) {
		this.mac = mac == null ? null : mac.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.state
	 * @return  the value of app_device.state
	 * @mbg.generated
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.state
	 * @param state  the value for app_device.state
	 * @mbg.generated
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.modify_time
	 * @return  the value of app_device.modify_time
	 * @mbg.generated
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.modify_time
	 * @param modifyTime  the value for app_device.modify_time
	 * @mbg.generated
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.c_time
	 * @return  the value of app_device.c_time
	 * @mbg.generated
	 */
	public Date getcTime() {
		return cTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.c_time
	 * @param cTime  the value for app_device.c_time
	 * @mbg.generated
	 */
	public void setcTime(Date cTime) {
		this.cTime = cTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_device.topic
	 * @return  the value of app_device.topic
	 * @mbg.generated
	 */
	public String getTopic() {
		return topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_device.topic
	 * @param topic  the value for app_device.topic
	 * @mbg.generated
	 */
	public void setTopic(String topic) {
		this.topic = topic == null ? null : topic.trim();
	}
}