package com.telrob.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppDeviceRecodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public AppDeviceRecodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMacIsNull() {
            addCriterion("mac is null");
            return (Criteria) this;
        }

        public Criteria andMacIsNotNull() {
            addCriterion("mac is not null");
            return (Criteria) this;
        }

        public Criteria andMacEqualTo(String value) {
            addCriterion("mac =", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotEqualTo(String value) {
            addCriterion("mac <>", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacGreaterThan(String value) {
            addCriterion("mac >", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacGreaterThanOrEqualTo(String value) {
            addCriterion("mac >=", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLessThan(String value) {
            addCriterion("mac <", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLessThanOrEqualTo(String value) {
            addCriterion("mac <=", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLike(String value) {
            addCriterion("mac like", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotLike(String value) {
            addCriterion("mac not like", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacIn(List<String> values) {
            addCriterion("mac in", values, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotIn(List<String> values) {
            addCriterion("mac not in", values, "mac");
            return (Criteria) this;
        }

        public Criteria andMacBetween(String value1, String value2) {
            addCriterion("mac between", value1, value2, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotBetween(String value1, String value2) {
            addCriterion("mac not between", value1, value2, "mac");
            return (Criteria) this;
        }

        public Criteria andAttribNameIsNull() {
            addCriterion("attrib_name is null");
            return (Criteria) this;
        }

        public Criteria andAttribNameIsNotNull() {
            addCriterion("attrib_name is not null");
            return (Criteria) this;
        }

        public Criteria andAttribNameEqualTo(String value) {
            addCriterion("attrib_name =", value, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameNotEqualTo(String value) {
            addCriterion("attrib_name <>", value, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameGreaterThan(String value) {
            addCriterion("attrib_name >", value, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameGreaterThanOrEqualTo(String value) {
            addCriterion("attrib_name >=", value, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameLessThan(String value) {
            addCriterion("attrib_name <", value, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameLessThanOrEqualTo(String value) {
            addCriterion("attrib_name <=", value, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameLike(String value) {
            addCriterion("attrib_name like", value, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameNotLike(String value) {
            addCriterion("attrib_name not like", value, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameIn(List<String> values) {
            addCriterion("attrib_name in", values, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameNotIn(List<String> values) {
            addCriterion("attrib_name not in", values, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameBetween(String value1, String value2) {
            addCriterion("attrib_name between", value1, value2, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribNameNotBetween(String value1, String value2) {
            addCriterion("attrib_name not between", value1, value2, "attribName");
            return (Criteria) this;
        }

        public Criteria andAttribValueIsNull() {
            addCriterion("attrib_value is null");
            return (Criteria) this;
        }

        public Criteria andAttribValueIsNotNull() {
            addCriterion("attrib_value is not null");
            return (Criteria) this;
        }

        public Criteria andAttribValueEqualTo(String value) {
            addCriterion("attrib_value =", value, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueNotEqualTo(String value) {
            addCriterion("attrib_value <>", value, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueGreaterThan(String value) {
            addCriterion("attrib_value >", value, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueGreaterThanOrEqualTo(String value) {
            addCriterion("attrib_value >=", value, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueLessThan(String value) {
            addCriterion("attrib_value <", value, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueLessThanOrEqualTo(String value) {
            addCriterion("attrib_value <=", value, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueLike(String value) {
            addCriterion("attrib_value like", value, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueNotLike(String value) {
            addCriterion("attrib_value not like", value, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueIn(List<String> values) {
            addCriterion("attrib_value in", values, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueNotIn(List<String> values) {
            addCriterion("attrib_value not in", values, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueBetween(String value1, String value2) {
            addCriterion("attrib_value between", value1, value2, "attribValue");
            return (Criteria) this;
        }

        public Criteria andAttribValueNotBetween(String value1, String value2) {
            addCriterion("attrib_value not between", value1, value2, "attribValue");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andProductKeyIsNull() {
            addCriterion("product_key is null");
            return (Criteria) this;
        }

        public Criteria andProductKeyIsNotNull() {
            addCriterion("product_key is not null");
            return (Criteria) this;
        }

        public Criteria andProductKeyEqualTo(String value) {
            addCriterion("product_key =", value, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyNotEqualTo(String value) {
            addCriterion("product_key <>", value, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyGreaterThan(String value) {
            addCriterion("product_key >", value, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyGreaterThanOrEqualTo(String value) {
            addCriterion("product_key >=", value, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyLessThan(String value) {
            addCriterion("product_key <", value, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyLessThanOrEqualTo(String value) {
            addCriterion("product_key <=", value, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyLike(String value) {
            addCriterion("product_key like", value, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyNotLike(String value) {
            addCriterion("product_key not like", value, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyIn(List<String> values) {
            addCriterion("product_key in", values, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyNotIn(List<String> values) {
            addCriterion("product_key not in", values, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyBetween(String value1, String value2) {
            addCriterion("product_key between", value1, value2, "productKey");
            return (Criteria) this;
        }

        public Criteria andProductKeyNotBetween(String value1, String value2) {
            addCriterion("product_key not between", value1, value2, "productKey");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretIsNull() {
            addCriterion("device_secret is null");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretIsNotNull() {
            addCriterion("device_secret is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretEqualTo(String value) {
            addCriterion("device_secret =", value, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretNotEqualTo(String value) {
            addCriterion("device_secret <>", value, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretGreaterThan(String value) {
            addCriterion("device_secret >", value, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretGreaterThanOrEqualTo(String value) {
            addCriterion("device_secret >=", value, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretLessThan(String value) {
            addCriterion("device_secret <", value, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretLessThanOrEqualTo(String value) {
            addCriterion("device_secret <=", value, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretLike(String value) {
            addCriterion("device_secret like", value, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretNotLike(String value) {
            addCriterion("device_secret not like", value, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretIn(List<String> values) {
            addCriterion("device_secret in", values, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretNotIn(List<String> values) {
            addCriterion("device_secret not in", values, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretBetween(String value1, String value2) {
            addCriterion("device_secret between", value1, value2, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andDeviceSecretNotBetween(String value1, String value2) {
            addCriterion("device_secret not between", value1, value2, "deviceSecret");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNull() {
            addCriterion("c_time is null");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNotNull() {
            addCriterion("c_time is not null");
            return (Criteria) this;
        }

        public Criteria andCTimeEqualTo(Date value) {
            addCriterion("c_time =", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotEqualTo(Date value) {
            addCriterion("c_time <>", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThan(Date value) {
            addCriterion("c_time >", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("c_time >=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThan(Date value) {
            addCriterion("c_time <", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThanOrEqualTo(Date value) {
            addCriterion("c_time <=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeIn(List<Date> values) {
            addCriterion("c_time in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotIn(List<Date> values) {
            addCriterion("c_time not in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeBetween(Date value1, Date value2) {
            addCriterion("c_time between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotBetween(Date value1, Date value2) {
            addCriterion("c_time not between", value1, value2, "cTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_device_recode
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}