package com.telrob.common.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class SysUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.mobile
	 * @mbg.generated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.nick
	 * @mbg.generated
	 */
	private String nick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.photo_path
	 * @mbg.generated
	 */
	private String photoPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.modity_time
	 * @mbg.generated
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
	private Date modityTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.ip
	 * @mbg.generated
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.c_time
	 * @mbg.generated
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
	private Date cTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.id
	 * @return  the value of sys_user.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.id
	 * @param id  the value for sys_user.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.mobile
	 * @return  the value of sys_user.mobile
	 * @mbg.generated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.mobile
	 * @param mobile  the value for sys_user.mobile
	 * @mbg.generated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.nick
	 * @return  the value of sys_user.nick
	 * @mbg.generated
	 */
	public String getNick() {
		return nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.nick
	 * @param nick  the value for sys_user.nick
	 * @mbg.generated
	 */
	public void setNick(String nick) {
		this.nick = nick == null ? null : nick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.name
	 * @return  the value of sys_user.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.name
	 * @param name  the value for sys_user.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 * @return  the value of sys_user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 * @param password  the value for sys_user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.photo_path
	 * @return  the value of sys_user.photo_path
	 * @mbg.generated
	 */
	public String getPhotoPath() {
		return photoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.photo_path
	 * @param photoPath  the value for sys_user.photo_path
	 * @mbg.generated
	 */
	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath == null ? null : photoPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.modity_time
	 * @return  the value of sys_user.modity_time
	 * @mbg.generated
	 */
	public Date getModityTime() {
		return modityTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.modity_time
	 * @param modityTime  the value for sys_user.modity_time
	 * @mbg.generated
	 */
	public void setModityTime(Date modityTime) {
		this.modityTime = modityTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.ip
	 * @return  the value of sys_user.ip
	 * @mbg.generated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.ip
	 * @param ip  the value for sys_user.ip
	 * @mbg.generated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.c_time
	 * @return  the value of sys_user.c_time
	 * @mbg.generated
	 */
	public Date getcTime() {
		return cTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.c_time
	 * @param cTime  the value for sys_user.c_time
	 * @mbg.generated
	 */
	public void setcTime(Date cTime) {
		this.cTime = cTime;
	}
}