package com.telrob.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.telrob.common.entity.AppAttribute;
import com.telrob.common.entity.AppAttributeExample;

public interface AppAttributeMapper extends BaseMapper<AppAttribute, AppAttributeExample, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    long countByExample(AppAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    int deleteByExample(AppAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    int insert(AppAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    int insertSelective(AppAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    List<AppAttribute> selectByExample(AppAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    AppAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppAttribute record, @Param("example") AppAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppAttribute record, @Param("example") AppAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppAttribute record);
}