package com.telrob.common.mapper;

import com.telrob.common.entity.AppDeviceRecode;
import com.telrob.common.entity.AppDeviceRecodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppDeviceRecodeMapper extends BaseMapper<AppDeviceRecode, AppDeviceRecodeExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    long countByExample(AppDeviceRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    int deleteByExample(AppDeviceRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    int insert(AppDeviceRecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    int insertSelective(AppDeviceRecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    List<AppDeviceRecode> selectByExample(AppDeviceRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    AppDeviceRecode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppDeviceRecode record, @Param("example") AppDeviceRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppDeviceRecode record, @Param("example") AppDeviceRecodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppDeviceRecode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device_recode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppDeviceRecode record);
}