package com.telrob.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.telrob.common.entity.AppDevice;
import com.telrob.common.entity.AppDeviceExample;

public interface AppDeviceMapper extends BaseMapper<AppDevice, AppDeviceExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    long countByExample(AppDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    int deleteByExample(AppDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    int insert(AppDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    int insertSelective(AppDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    List<AppDevice> selectByExample(AppDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    AppDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppDevice record, @Param("example") AppDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppDevice record, @Param("example") AppDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppDevice record);
}