package com.telrob.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.telrob.common.entity.AppDevice;
import com.telrob.common.entity.AppDeviceExample;

public interface AppDeviceMapper extends BaseMapper<AppDevice, AppDeviceExample, Integer> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	long countByExample(AppDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	int deleteByExample(AppDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	int insert(AppDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	int insertSelective(AppDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	List<AppDevice> selectByExample(AppDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	AppDevice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") AppDevice record, @Param("example") AppDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") AppDevice record, @Param("example") AppDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(AppDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_device
	 * @mbg.generated
	 */
	int updateByPrimaryKey(AppDevice record);
	/**
	 * 校验设备登录,返回topic
	 * @param productKey
	 * @param deviceSecret
	 * @return
	 */
	AppDevice deviceLogin(@Param("productKey")String productKey, @Param("mac")String mac);
}