package com.telrob.common.mapper;

import com.telrob.common.entity.AppProject;
import com.telrob.common.entity.AppProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppProjectMapper extends BaseMapper<AppProject, AppProjectExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    long countByExample(AppProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    int deleteByExample(AppProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    int insert(AppProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    int insertSelective(AppProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    List<AppProject> selectByExample(AppProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    AppProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppProject record, @Param("example") AppProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppProject record, @Param("example") AppProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppProject record);
}