package com.telrob.common.mapper;

import com.telrob.common.entity.SysMenu;
import com.telrob.common.entity.SysMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuMapper extends BaseMapper<SysMenu, SysMenuExample, Integer>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	long countByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	int deleteByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	int insert(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	int insertSelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	List<SysMenu> selectByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	SysMenu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_menu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SysMenu record);
}